export const LOGGABLE_SET_ORIGIN = 'LOGGABLE_SET_ORIGIN';
export const LOGGABLE_SET_DESTINATION = 'LOGGABLE_SET_DESTINATION';
export const LOGGABLE_SET_RESULTS = 'LOGGABLE_SET_RESULTS';
export const LOGGABLE_ADD_RESULTS = 'LOGGABLE_ADD_RESULTS';
export const LOGGABLE_SET_TRAVEL = 'LOGGABLE_SET_TRAVEL';
export const BEGIN_ASYNC_PROCESS = 'BEGIN_ASYNC_PROCESS';
export const END_ASYNC_PROCESS = 'END_ASYNC_PROCESS';
