export const SET_ORIGIN = 'SET_ORIGIN';
export const SET_DESTINATION = 'SET_DESTINATION';
export const BEGIN_ASYNC_PROCESS = 'BEGIN_ASYNC_PROCESS';
export const END_ASYNC_PROCESS = 'END_ASYNC_PROCESS';
